# **************************************** Static CAN IDs ****************************************

# Charger
CHARGER_BMS = 0x1806e5f4
CHARGER_CCS = 0x18ff50e5

# IVT
IVT_COMMAND = 0x411
IVT_DEBUG = 0x510
IVT_RESPONSE = 0x511
IVT_CURRENT = 0x521
IVT_VOLTAGE_1 = 0x522
IVT_VOLTAGE_2 = 0x523
IVT_VOLTAGE_3 = 0x524
IVT_TEMPERATURE = 0x525
IVT_POWER = 0x526
IVT_CURRENT_COUNTER = 0x527
IVT_ENERGY_COUNTER = 0x528

# RMS
RMS_VOLTAGE = 0xa7
RMS_MOTOR = 0xa5
RMS_COMMAND = 0xc0
RMS_PARAMETER = 0xc1

# APPS
APPS_TPS = 0x80

# **************************************** Dynamic CAN IDs ****************************************

# BMS
BMS_TEMPERATURE = 0x0
BMS_ENABLED_TEMPERATURE_SENSORS = 0x1
BMS_VOLTAGE = 0x2
BMS_STATE = 0x3
BMS_BALANCE = 0x4
BMS_DART1_REQUESTED_FAN_SPEEDS = 0x5
BMS_DART2_REQUESTED_FAN_SPEEDS = 0x6

# ICS
ICS_BUTTON_STATE = 0x7
ICS_TEST = 0x8

# APPS
APPS_BRAKE_PEDAL = 0x9
APPS_BSPD = 0xa

# ART
DART_DART1_MEASURED_FAN_SPEEDS = 0xb
DART_DART2_MEASURED_FAN_SPEEDS = 0xc
